import { Project } from './src/types';

export const PROJECTS: Project[] = [
  {
    id: '1',
    name: 'PDFify',
    category: 'Full Stack',
    date: '2025',
    image: 'https://opengraph.githubassets.com/1/guptaji9630/pdfify-frontend',
    description: 'Full-stack PDF conversion platform with React frontend and Node.js backend. Features file upload, cloud storage integration, batch processing, and real-time progress tracking.',
    githubUrl: 'https://github.com/guptaji9630/pdfify-frontend',
    liveDemo: 'https://pdfify.vercel.app',
    techStack: ['React', 'Node.js', 'TypeScript', 'MongoDB', 'Tailwind CSS', 'Cloudinary'],
    highlights: ['File upload with drag & drop', 'Cloudinary integration for storage', 'Batch processing support', 'Real-time progress tracking', 'Responsive modern UI'],
  },
  {
    id: '2',
    name: 'Claude AI Proxy',
    category: 'Backend/API',
    date: '2025',
    image: 'https://opengraph.githubassets.com/1/guptaji9630/Claude-ai-proxy',
    description: 'Node.js proxy server for Claude AI with rate limiting, authentication, streaming response support, and request/response logging. Deployed as a scalable microservice.',
    githubUrl: 'https://github.com/guptaji9630/Claude-ai-proxy',
    liveDemo: 'https://claude-proxy.vercel.app',
    techStack: ['Node.js', 'Express', 'TypeScript', 'Vercel', 'Streaming', 'Rate Limiting'],
    highlights: ['Streaming response support', 'Rate limiting & authentication', 'Request/response logging', 'Scalable microservice architecture', 'Vercel serverless deployment'],
  },
  {
    id: '3',
    name: 'Quickdabba',
    category: 'Full Stack',
    date: '2024',
    image: 'https://opengraph.githubassets.com/1/guptaji9630/Quickdabba-',
    description: 'Quick commerce platform for grocery delivery. Features real-time order tracking, payment integration, inventory management, admin dashboard, and multi-vendor support.',
    githubUrl: 'https://github.com/guptaji9630/Quickdabba-',
    liveDemo: 'https://quickdabba.vercel.app',
    techStack: ['React', 'Node.js', 'MongoDB', 'Socket.io', 'Stripe', 'Redis', 'Docker'],
    highlights: ['Real-time order tracking (Socket.io)', 'Stripe payment integration', 'Multi-vendor marketplace', 'Admin dashboard with analytics', 'Redis caching for performance'],
  },
  {
    id: '4',
    name: 'FitForge',
    category: 'MERN App',
    date: '2025',
    image: 'https://opengraph.githubassets.com/1/guptaji9630/FitForge',
    description: 'Full-stack fitness tracker with GraphQL API, real-time workout analytics, progress photo comparisons, personalized workout plans, and social features.',
    githubUrl: 'https://github.com/guptaji9630/FitForge',
    liveDemo: 'https://fitforge.vercel.app',
    techStack: ['React', 'Node.js', 'GraphQL', 'MongoDB', 'Apollo', 'Tailwind CSS', 'Jest', 'Playwright'],
    highlights: ['GraphQL API with Apollo', 'Real-time workout analytics', 'Progress photo comparisons', 'Personalized workout plans', 'Jest/Playwright test coverage'],
  },
  {
    id: '5',
    name: 'Trail Management System',
    category: 'Enterprise',
    date: '2025',
    image: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=500&fit=crop',
    description: 'Enterprise trial management platform at Agmatix. Contributed full-stack features, automated testing (Jest/Playwright), API development, and CI/CD pipeline improvements.',
    githubUrl: '',
    liveDemo: '',
    techStack: ['React', 'Node.js', 'GraphQL', 'PostgreSQL', 'Jest', 'Playwright', 'Docker', 'GitHub Actions'],
    highlights: ['Full-stack feature development', 'Automated testing (85%+ coverage)', 'GraphQL API optimization', 'CI/CD pipeline with GitHub Actions', 'Docker containerization'],
  },
  {
    id: '6',
    name: 'Portfolio OS (GuptaOS)',
    category: 'Desktop App',
    date: '2026',
    image: 'https://opengraph.githubassets.com/1/guptaji9630/podfolio',
    description: 'macOS-style desktop environment built with React 19, Motion (Framer Motion v13), Vite 6, and Tailwind CSS 4. Features window management, dock, terminal, AI chat, and games.',
    githubUrl: 'https://github.com/guptaji9630/podfolio',
    liveDemo: 'https://podfolio-two.vercel.app',
    techStack: ['React 19', 'Motion', 'Vite 6', 'Tailwind CSS 4', 'TypeScript', 'html2canvas', 'jsPDF'],
    highlights: ['Window management system', 'Custom dock with magnification', 'Interactive terminal', 'AI chat integration', 'Built-in games (Dino, Pong)'],
  },
];